language: go

go:
  - 1.13
  - tip

install:
  - go get -u golang.org/x/lint/golint

script:
  - make fmt vet lint unit_test build install

deploy:
  - provider: script
    skip_cleanup: true
    script: ext/goreleaser release
    on:
      go: '1.13'
      tags: true

notifications:
  email: false
